spring:
  application:
    name: shopApp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: vi
logging:
  level:
    root: info
jwt:
  expiration: 2592000 #Giá trị expiration <=> 30 ngày (30 * 24 * 60 * 60 giây)
  secretKey: 2YPhJUryN2Rm6rxeTYcIQSR4/UuM39MGKU0R4ilcFOo=
server:
  port: 8088
api:
  prefix: api/v1
# Chỉ định thư mục lưu ảnh tạm thời trên local
upload:
  path: E:/SpringProject/shopapp-BE/shopapp/src/main/resources/uploads

